run vlfeat/toolbox/vl_setup

if exist('vl_nnconv') ~= 3
  run matconvnet/matlab/vl_setupnn
  if exist('vl_nnconv') ~= 3
    warning('MatConvNet not compiled, attempting to fix...') ;
    copyfile(...
      'matconvnet/matlab/src/vl_nnconv.cu', ...
      'matconvnet/matlab/src/vl_nnconv.cpp') ;
    mex('matconvnet/matlab/src/vl_nnconv.cpp', ...
      'matconvnet/matlab//src/bits/im2col.cpp', ...
      'matconvnet/matlab//src/bits/subsample.cpp', ...
      '-Imatconvnet/matlab/src',...
      '-lmwblas') ;
  end
end
