mkdir('../mex');
mex -outdir ../mex -largeArrayDims -lmwblas vl_nnconv.cpp bits/im2col.cpp bits/normalize.cpp bits/pooling.cpp bits/subsample.cpp
mex -outdir ../mex -largeArrayDims -lmwblas vl_nnnormalize.cpp bits/im2col.cpp bits/normalize.cpp bits/pooling.cpp bits/subsample.cpp
mex -outdir ../mex -largeArrayDims -lmwblas vl_nnpool.cpp bits/im2col.cpp bits/normalize.cpp bits/pooling.cpp bits/subsample.cpp
mex  -outdir ../mex -largeArrayDims vl_imreadjpeg.cpp libjpeg/jaricom.c   libjpeg/jchuff.c    libjpeg/jcprepct.c  libjpeg/jdatasrc.c  libjpeg/jdmarker.c  libjpeg/jfdctflt.c  libjpeg/jmemmgr.c   ...
libjpeg/jcapimin.c  libjpeg/jcinit.c    libjpeg/jcsample.c  libjpeg/jdcoefct.c  libjpeg/jdmaster.c  libjpeg/jfdctfst.c  libjpeg/jmemnobs.c  ...
libjpeg/jcapistd.c  libjpeg/jcmainct.c  libjpeg/jctrans.c   libjpeg/jdcolor.c   libjpeg/jdmerge.c   libjpeg/jfdctint.c  libjpeg/jquant1.c   ...
libjpeg/jcarith.c   libjpeg/jcmarker.c  libjpeg/jdapimin.c  libjpeg/jddctmgr.c  libjpeg/jdpostct.c  libjpeg/jidctflt.c  libjpeg/jquant2.c   ...
libjpeg/jccoefct.c  libjpeg/jcmaster.c  libjpeg/jdapistd.c  libjpeg/jdhuff.c    libjpeg/jdsample.c  libjpeg/jidctfst.c  libjpeg/jutils.c    ...
libjpeg/jccolor.c   libjpeg/jcomapi.c   libjpeg/jdarith.c   libjpeg/jdinput.c   libjpeg/jdtrans.c   libjpeg/jidctint.c  ...
libjpeg/jcdctmgr.c  libjpeg/jcparam.c   libjpeg/jdatadst.c  libjpeg/jdmainct.c  libjpeg/jerror.c -Lpthread -lpthreadVC2 

fprintf('Compile Finished !!!');